live_config_reload = true

[colors.normal]
# black = "0x1E2127"
# blue = "0xBD93F9"
# cyan = "0x8BE9FD"
# green = "0x50FA7B"
# magenta = "0xFF79C6"
# red = "0xFF5555"
# white = "0xBFBFBF"
# yellow = "0xF1FA8C"

# gruvbox
black = '0x665c54'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xe78a4e'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xdfbf8e'

[colors.primary]
# background = "0x1E2127"
# foreground = "0xF8F8F2"

# gruvbox
background = "0x282828"
foreground = "0xdfbf8e"

[colors.bright]
black = '0x928374'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xe3a84e'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xdfbf8e'

[font.normal]
family = "SourceCodeVf"
style = "Bold Italic"

[window]
dynamic_padding = false

[window.padding]
x = 20
y = 20
